# Generated by Django 4.0 on 2021-12-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='byword',
            field=models.CharField(default='人生格言', max_length=128, verbose_name='人生格言'),
        ),
        migrations.AddField(
            model_name='student',
            name='constellation',
            field=models.IntegerField(choices=[(0, '白羊座'), (1, '金牛座'), (2, '双子座'), (3, '巨蟹座'), (4, '狮子座'), (5, '处女座'), (6, '天秤座'), (7, '天蝎座'), (8, '射手座'), (9, '魔羯座'), (10, '水平座'), (11, '双鱼座')], default=0, verbose_name='性别'),
        ),
    ]
