# Generated by Django 4.0 on 2021-12-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_byword'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='byword',
            field=models.TextField(blank=True, max_length=128, verbose_name='人生格言'),
        ),
    ]
