# Generated by Django 4.0 on 2021-12-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_byword'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='星座名字')),
            ],
            options={
                'verbose_name': '星座信息',
                'verbose_name_plural': '星座信息',
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='constellation',
            field=models.IntegerField(choices=[(0, '白羊座'), (1, '金牛座'), (2, '双子座'), (3, '巨蟹座'), (4, '狮子座'), (5, '处女座'), (6, '天秤座'), (7, '天蝎座'), (8, '射手座'), (9, '魔羯座'), (10, '水平座'), (11, '双鱼座')], default=0, verbose_name='星座'),
        ),
    ]
