# Generated by Django 4.0 on 2021-12-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_starinfo_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='SexInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='性别')),
                ('value', models.IntegerField(default=0, verbose_name='数值')),
            ],
            options={
                'verbose_name': '男女比例',
                'verbose_name_plural': '男女比例',
            },
        ),
    ]
