# Generated by Django 4.0 on 2021-12-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_geoinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnhuiGeoInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='姓名')),
                ('value', models.CharField(default=0, max_length=128, verbose_name='家乡坐标')),
                ('coords', models.CharField(default=0, max_length=128, verbose_name='箭头坐标')),
            ],
        ),
    ]
